"""Thi is Problem 45 of ProjectEuler

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle                Tn=n(n+1)/2             1, 3, 6, 10, 15, ...
Pentagonal              Pn=n(3n-1)/2             1, 5, 12, 22, 35, ...
Hexagonal               Hn=n(2n-1)               1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal."""

__author__ = "Andrew Phoenix"

import eulib

# This Method was intended to search along the line of hex numbers
# and break out when it found something that was also a tri and a
# pent. I think it's a little processor crazy.

for x in range(144, 1000000):
    H = eulib.genhex(x)
    print
    H,
    if eulib.ispent(H) == True:
        if eulib.istri(H) == True:
            print
            H, 'is the answer. It is H of', x
            break
